title: My github learning test page
author: Dan Crosby
email: Cro18023@byui.edu
description: > # this means to ignore newlines until "baseurl:"
  Hello everyone!

# social links
twitter_username: dc21001
github_username:  crosby-dan

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-time-machine
